databases:
  - name: thepacificmart-db
    plan: free
    databaseName: thepacificmart
    user: thepacificmart

services:
  - type: web
    plan: free
    name: thepacificmart
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn factors_Ecom.wsgi:application --timeout 30 --workers 1 --max-requests 1000 --max-requests-jitter 50'
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: thepacificmart-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "pacific-mart.onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://pacific-mart.onrender.com"
      - key: WEB_CONCURRENCY
        value: "1"
